<!DOCTYPE html>
<html lang="en">
<head>
    <title>BUYSELL</title>
</head>

<body>
    <h1>BUYSELL</h1><hr>
    <h4>Подробная информация о товаре</h4>
    <b>Название товара: </b>${product.title}<br>
    <b>Описание товара: </b>${product.description}<br>
    <b>Цена товара: </b>${product.price}<br>
    <b>Город: </b>${product.city}<br>
    <b>Автор: </b>${product.description}<br>
    <hr>

    <form action="/product/delete/${product.id}" method="POST">
        <input type="submit" value="Удалить товар"/>
    </form>
</body>
</html>